### ISSUE TITLE
Request: Dark visual theme

### ISSUE THREAD

**Issue by Zhnigo** [FFXIVCrafting/ffxivcrafting#313] opened 2017-06-12 00:43 UTC
Love the service, but the white backround is burning my eyes sitting there on the second monitor. Would you consider a "night mode" style? Thanks.

**Comment by Tickthokk** [comment] 2017-06-12 12:44
Duplicate of #307.  It's in the woks :)

**Closed by Tickthokk** 2017-06-12 12:44 UTC

**Comment by Zhnigo** [comment] 2017-06-12 14:31
<3
